// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRule():Promise<void>;

export function CreateRule(arg1:number):Promise<boolean>;

export function DelRule():Promise<boolean>;

export function GetRuleStatus():Promise<boolean>;

export function Greet(arg1:string):Promise<string>;
