// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckRule() {
  return window['go']['main']['App']['CheckRule']();
}

export function CreateRule(arg1) {
  return window['go']['main']['App']['CreateRule'](arg1);
}

export function DelRule() {
  return window['go']['main']['App']['DelRule']();
}

export function GetRuleStatus() {
  return window['go']['main']['App']['GetRuleStatus']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
